### ISSUE TITLE
Rubric Score

### ISSUE THREAD

**Issue by sen1** [king-shak/dvp-u3-constellations#2]
## Rubric Score
 
### Criteria 1: Matplotlib and CSV
* 4 (Exceeds Expectations)
* All libraries and data were imported properly.
 
### Criteria 2: Implementation of 2D Visualization
* 4 (Exceeds Expectations)
* Nice work.
 
### Criteria 3: Implementation of 3D Visualization
* 4 (Exceeds Expectations)
* One minor comment made. However, all worked as expected.
 
### Overall Score: 12/12
Excellent work. 👏

**Comment by king-shak** [comment]
Alright Thanks!
